controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
show_article:
    path: '/article/{id}'
    controller: 'App\Controller\ArticleController::show'
    methods: ['GET']

